development:
  adapter: postgresql
  encoding: unicode
  database: TASKS_APP_DEVELOPMENT
  pool: 2
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: TASKS_APP_PRODUCTION
  pool: 2
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
